services:
  web:
    image: azymik/flask--udemy-course-rest-api-with-flask-and-python-in-2024--your-first-rest-api
    ports:
      - '5001:5000'
      - '5002:80'
    volumes:
      - type: bind
        source: ./
        target: /app
    command: /home/devuser/.venv/bin/flask run --host=0.0.0.0
    # command: /home/devuser/.venv/bin/gunicorn --bind 0.0.0.0:80 'app:create_app()'
    depends_on:
      - db
  db:
    image: postgres:16.3
    volumes:
      - type: bind
        source: ./pgdata
        target: /var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: myapp